### ISSUE TITLE
Ms_gmr_strat Backtest Issue

### ISSUE THREAD

**Issue by kliu3638** [northwesternfintech/Desk-Alpha#27]
Ran the following code:
```python
import testStrat


s = Strategy(
    algo=None,
    transaction_cost=0.0001,
    start_balance=10000,
    name='test'
)


a = testStrat.Ms_gmr_strat()
s.set_algo(a)

s.back_testing()
```

Outputs the following error:
> kevin@kevins-mbp-2 backtesting % /opt/home
> brew/bin/python3 /Users/kevin/Documents/Gi
> tHub/Core/core/backtesting/strategy.py
> [['buy', 'test', 1050, 1], ['sell', 'test', 1040, 1]]
> 
>  Started
> Traceback (most recent call last):
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/strategy.py", line 484, in <module>
>     s.back_testing()
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/strategy.py", line 181, in back_testing
>     tickOrders = self.algo.update(ticker_data_dict)
> TypeError: Ms_gmr_strat.update() takes 1 positional argument but 2 were given

Not sure if helpful, but the backtester calls update() on a dictionary with the tickers as dictionary keys and open values as dictionary values.

**Comment by jiale0402** [comment]
please be informed that a dict of prices will be feed to the algo every tick, so account for it when writing your update function

**Comment by kliu3638** [comment]
also init using kwargs

**Comment by kliu3638** [comment]
also need to init using kwargs

**Comment by echavemann** [comment]
deprecating, gj
