### ISSUE TITLE
FibonacciMultiStock Backtest Issue

### ISSUE THREAD

**Issue by kliu3638** [northwesternfintech/Desk-Alpha#28]
Ran the following code:
```python
import testStrat


s = Strategy(
    algo=None,
    transaction_cost=0.0001,
    start_balance=10000,
    name='test'
)


a = testStrat.FibonacciMultiStock(10, 1, **{"tickers": s.tickers})
s.set_algo(a)

s.back_testing()
```

Initially outputs the following error:

> Traceback (most recent call last):
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/strategy.py", line 484, in <module>
>     s.back_testing()
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/strategy.py", line 183, in back_testing
>     tickOrders = list(tickOrders.items())
> AttributeError: 'NoneType' object has no attribute 'items'

After analyzing the code, I cut line 115 of the Fibonacci algorithm:
```python
return self.orders
```
and pasted it in line 131, so that way the update() method returns the ticks instead of updateSingle(). I think this should fix the above error, but double check the code to make sure.

Now, the algorithm outputs the following error:

> Traceback (most recent call last):
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/strategy.py", line 484, in <module>
>     s.back_testing()
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/strategy.py", line 181, in back_testing
>     tickOrders = self.algo.update(ticker_data_dict)
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/testStrat.py", line 126, in update
>     self.calculateRetracementSingle(ticker)
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/testStrat.py", line 74, in calculateRetracementSingle
>     self.bands[ticker][len(self.bands)-1-i] = l + (r-l) * self.ratios[i]
> IndexError: list assignment index out of range

However after replacing the line in the code that I ran in the backtester:
```python
a = testStrat.FibonacciMultiStock(10, 1, **{"tickers": s.tickers})
```
with:
```python
a = testStrat.FibonacciMultiStock(**{"tickers": s.tickers})
```
the code runs (but very slowly: 140 seconds to backtest each day. Gary is dealing with that issue right now)

Please make sure that the algorithm runs for all inputted scope and ordersWhenHitsBand values, and if there are values that should not work make note of it in documentation.

**Comment by kliu3638** [comment]
UPDATE:

Gary fixed the backtesting algorithm. I am now able to backtest all days without it taking forever to run.

I ran the code that I mentioned at the end:
```python
import testStrat


s = Strategy(
    algo=None,
    transaction_cost=0.0001,
    start_balance=10000,
    name='test'
)


a = testStrat.FibonacciMultiStock(**{"tickers": s.tickers})
s.set_algo(a)

s.back_testing()
```
And I am getting the exact same error as before:

> Traceback (most recent call last):
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/strategy.py", line 473, in <module>
>     s.back_testing()
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/strategy.py", line 179, in back_testing
>     tickOrders = self.algo.update(ticker_data_dict)
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/testStrat.py", line 126, in update
>     self.calculateRetracementSingle(ticker)
>   File "/Users/kevin/Documents/GitHub/Core/core/backtesting/testStrat.py", line 74, in calculateRetracementSingle
>     self.bands[ticker][len(self.bands)-1-i] = l + (r-l) * self.ratios[i]
> IndexError: list assignment index out of range

Compared to using scope = 10 and ordersWhenHitsBand = 1, the backtester is backtest more data before reaching the error, but is still facing the same error.

So we still have the same issue: Please make sure that the algorithm runs for all inputted scope and ordersWhenHitsBand values, and if there are values that should not work make note of it in documentation.

**Comment by echavemann** [comment]
deprecating. good work.
